# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac8a440475b10d5ccb827b048eb251bcfc26f9602b3570d3e45b41068fb634a6ef90ade2a7c5ac3734c7af04f75292331874e8b8cd023116eed084c813420452

test:
  secret_key_base: 9090a722776551e14b2968acccfcafd52280a264dd1bbe14127fc74a103aa30832bca0b9dcccf6ea2e3170b7846b0ceda81538a11b7939e0c993a8b3398be6bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
